# Generated by Django 4.2.16 on 2024-09-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="clientes",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
